### ISSUE TITLE
active job 5.0.0 support?

### ISSUE THREAD

**Issue by DoctorOgg** [cdale77/active_job_status#16]
any chance of active job 5.0.0 support?

```
Bundler could not find compatible versions for gem "activejob":
  In snapshot (Gemfile.lock):
    activejob (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        activejob (= 5.0.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) was resolved to 5.0.0, which depends on
        activejob (= 5.0.0)

    active_job_status (~> 1.1) was resolved to 1.1.0, which depends on
      activejob (~> 4.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by cdale77** [comment]
hey @neallawson thanks for the report. I just pushed a change that simply allows rails 5. I haven't tested it out yet, but it should work thanks to the recent changes that allow you to do `include ActiveJobStatus::Hooks` instead of inheriting from `TrackableJob`. 

You can give it a try from master now. As soon as I can do some more testing I'll release a new version.

**Comment by cdale77** [comment]
You should be set now! v1.2 supports Rails 5, and is now published.
